-- https://leetcode.com/problems/immediate-food-delivery-ii/?envType=study-plan-v2&envId=top-sql-50

-- Write your MySQL query statement below

WITH CTE AS
(SELECT *,RANK() OVER(PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) 
AS ORDER_NUMBER , CASE WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN
'IMMEDIATE' ELSE 'SCHEDULED' END AS ORDER_TYPE
FROM DELIVERY)

SELECT ROUND(SUM(CASE WHEN ORDER_TYPE='IMMEDIATE' THEN 1 ELSE 0 END)/COUNT(*)*100,2)
AS IMMEDIATE_PERCENTAGE
FROM CTE
WHERE ORDER_NUMBER = 1
